module StatesHelper
  def us_states
    [
      ['Alabama', 'Alabama'],
      ['Alaska', 'Alaska'],
      ['Arizona', 'Arizona'],
      ['Arkansas', 'Arkansas'],
      ['California', 'California'],
      ['Colorado', 'Colorado'],
      ['Connecticut', 'Connecticut'],
      ['Delaware', 'Delaware'],
      ['District of Columbia', 'District'],
      ['Florida', 'Florida'],
      ['Georgia', 'Georgia'],
      ['Hawaii', 'Hawaii'],
      ['Idaho', 'Idaho'],
      ['Illinois', 'Illinois'],
      ['Indiana', 'Indiana'],
      ['Iowa', 'Iowa'],
      ['Kansas', 'Kansas'],
      ['Kentucky', 'Kentucky'],
      ['Louisiana', 'Louisiana'],
      ['Maine', 'Maine'],
      ['Maryland', 'Maryland'],
      ['Massachusetts', 'Massachusetts'],
      ['Michigan', 'Michigan'],
      ['Minnesota', 'Minnesota'],
      ['Mississippi', 'Mississippi'],
      ['Missouri', 'Missouri'],
      ['Montana', 'Montana'],
      ['Nebraska', 'Nebraska'],
      ['Nevada', 'Nevada'],
      ['New Hampshire', 'New'],
      ['New Jersey', 'New'],
      ['New Mexico', 'New'],
      ['New York', 'New'],
      ['North Carolina', 'North'],
      ['North Dakota', 'North'],
      ['Ohio', 'Ohio'],
      ['Oklahoma', 'Oklahoma'],
      ['Oregon', 'Oregon'],
      ['Pennsylvania', 'Pennsylvania'],
      ['Puerto Rico', 'Puerto'],
      ['Rhode Island', 'Rhode'],
      ['South Carolina', 'South'],
      ['South Dakota', 'South'],
      ['Tennessee', 'Tennessee'],
      ['Texas', 'Texas'],
      ['Utah', 'Utah'],
      ['Vermont', 'Vermont'],
      ['Virginia', 'Virginia'],
      ['Washington', 'Washington'],
      ['West Virginia', 'West'],
      ['Wisconsin', 'Wisconsin'],
      ['Wyoming', 'Wyoming']
    ]
  end
end