require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AcceptableContactRolesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # AcceptableContactRole. As you add validations to AcceptableContactRole, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AcceptableContactRolesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all acceptable_contact_roles as @acceptable_contact_roles" do
      acceptable_contact_role = AcceptableContactRole.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:acceptable_contact_roles)).to eq([acceptable_contact_role])
    end
  end

  describe "GET show" do
    it "assigns the requested acceptable_contact_role as @acceptable_contact_role" do
      acceptable_contact_role = AcceptableContactRole.create! valid_attributes
      get :show, {:id => acceptable_contact_role.to_param}, valid_session
      expect(assigns(:acceptable_contact_role)).to eq(acceptable_contact_role)
    end
  end

  describe "GET new" do
    it "assigns a new acceptable_contact_role as @acceptable_contact_role" do
      get :new, {}, valid_session
      expect(assigns(:acceptable_contact_role)).to be_a_new(AcceptableContactRole)
    end
  end

  describe "GET edit" do
    it "assigns the requested acceptable_contact_role as @acceptable_contact_role" do
      acceptable_contact_role = AcceptableContactRole.create! valid_attributes
      get :edit, {:id => acceptable_contact_role.to_param}, valid_session
      expect(assigns(:acceptable_contact_role)).to eq(acceptable_contact_role)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AcceptableContactRole" do
        expect {
          post :create, {:acceptable_contact_role => valid_attributes}, valid_session
        }.to change(AcceptableContactRole, :count).by(1)
      end

      it "assigns a newly created acceptable_contact_role as @acceptable_contact_role" do
        post :create, {:acceptable_contact_role => valid_attributes}, valid_session
        expect(assigns(:acceptable_contact_role)).to be_a(AcceptableContactRole)
        expect(assigns(:acceptable_contact_role)).to be_persisted
      end

      it "redirects to the created acceptable_contact_role" do
        post :create, {:acceptable_contact_role => valid_attributes}, valid_session
        expect(response).to redirect_to(AcceptableContactRole.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved acceptable_contact_role as @acceptable_contact_role" do
        post :create, {:acceptable_contact_role => invalid_attributes}, valid_session
        expect(assigns(:acceptable_contact_role)).to be_a_new(AcceptableContactRole)
      end

      it "re-renders the 'new' template" do
        post :create, {:acceptable_contact_role => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested acceptable_contact_role" do
        acceptable_contact_role = AcceptableContactRole.create! valid_attributes
        put :update, {:id => acceptable_contact_role.to_param, :acceptable_contact_role => new_attributes}, valid_session
        acceptable_contact_role.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested acceptable_contact_role as @acceptable_contact_role" do
        acceptable_contact_role = AcceptableContactRole.create! valid_attributes
        put :update, {:id => acceptable_contact_role.to_param, :acceptable_contact_role => valid_attributes}, valid_session
        expect(assigns(:acceptable_contact_role)).to eq(acceptable_contact_role)
      end

      it "redirects to the acceptable_contact_role" do
        acceptable_contact_role = AcceptableContactRole.create! valid_attributes
        put :update, {:id => acceptable_contact_role.to_param, :acceptable_contact_role => valid_attributes}, valid_session
        expect(response).to redirect_to(acceptable_contact_role)
      end
    end

    describe "with invalid params" do
      it "assigns the acceptable_contact_role as @acceptable_contact_role" do
        acceptable_contact_role = AcceptableContactRole.create! valid_attributes
        put :update, {:id => acceptable_contact_role.to_param, :acceptable_contact_role => invalid_attributes}, valid_session
        expect(assigns(:acceptable_contact_role)).to eq(acceptable_contact_role)
      end

      it "re-renders the 'edit' template" do
        acceptable_contact_role = AcceptableContactRole.create! valid_attributes
        put :update, {:id => acceptable_contact_role.to_param, :acceptable_contact_role => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested acceptable_contact_role" do
      acceptable_contact_role = AcceptableContactRole.create! valid_attributes
      expect {
        delete :destroy, {:id => acceptable_contact_role.to_param}, valid_session
      }.to change(AcceptableContactRole, :count).by(-1)
    end

    it "redirects to the acceptable_contact_roles list" do
      acceptable_contact_role = AcceptableContactRole.create! valid_attributes
      delete :destroy, {:id => acceptable_contact_role.to_param}, valid_session
      expect(response).to redirect_to(acceptable_contact_roles_url)
    end
  end

end
